name: Build projects

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Determine Iodine version
      id: version
      run: echo ::set-output name=version::$(cat VERSION)
    - name: Build root projects
      run: |
        chmod +x gradlew 
        ./gradlew shadowJar publishToMavenLocal --warning-mode all
    - name: Upload Bukkit plugin JAR
      uses: actions/upload-artifact@v1
      with:
        name: Iodine-Bukkit-${{ steps.version.outputs.version }}.jar
        path: bukkit/build/libs/Iodine-Bukkit-${{ steps.version.outputs.version }}.jar
    - name: Build forge-1_14_4
      run: |
        cd forge-1_14_4
        chmod +x gradlew 
        ./gradlew jar --warning-mode all
        cd ..
    - name: Upload Forge mod JAR
      uses: actions/upload-artifact@v1
      with:
        name: Iodine-Forge-1_14_4-${{ steps.version.outputs.version }}.jar
        path: forge-1_14_4/build/libs/Iodine-Forge-1_14_4-${{ steps.version.outputs.version }}.jar
